package com.youtubeauto.video.api;

import com.youtubeauto.video.config.VideoProperties;
import com.youtubeauto.video.service.SunoMusicClient;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Map;
import java.util.UUID;

/**
 * Song Mode endpoint — turns lyrics into a vocal track + a karaoke (instrumental)
 * counterpart. Orchestrator calls this when motionMode=song.
 *
 * Both files are written under {workRoot}/{jobId}/song/.
 *   - song.mp3       : full song with vocals (used as primary audio in assembly)
 *   - karaoke.mp3    : same backing track, no vocals (bonus output)
 */
@Slf4j
@RestController
@RequestMapping("/api/v1/songs")
@RequiredArgsConstructor
public class SongController {

    private final SunoMusicClient suno;
    private final VideoProperties props;

    /** Emotional arc appended to every instrumental prompt (Story E2 slice). Kept
     *  free of mood-bucket keywords so it never flips the chosen bucket. */
    private static final String SCORE_ARC =
            "Shape the piece with a clear emotional arc to match the story: begin "
            + "small and intriguing, grow and add momentum through the middle, lift "
            + "to a bright, triumphant high point about three-quarters of the way "
            + "through, then ease down into a contented, settled finish. Keep dynamic "
            + "light and shade — not one flat repeating loop.";

    public record GenerateRequest(UUID jobId, String lyrics, String style, String chorus) {}

    public record GenerateResponse(String songPath, String karaokePath, boolean enabled) {}

    public record InstrumentalRequest(UUID jobId, String mood) {}

    public record InstrumentalResponse(String musicPath, boolean enabled) {}

    /**
     * Normal-episode background music — an ORIGINAL kids-cartoon INSTRUMENTAL
     * generated by Suno from the episode mood. Replaces the small royalty-free
     * library when a SUNO_API_KEY is configured; otherwise returns enabled=false
     * so the orchestrator falls back to bible/music.
     */
    @PostMapping("/instrumental")
    public ResponseEntity<InstrumentalResponse> instrumental(@RequestBody InstrumentalRequest req)
            throws Exception {
        if (!suno.isEnabled()) {
            log.warn("Suno not enabled — instrumental falling back to royalty-free library");
            return ResponseEntity.ok(new InstrumentalResponse(null, false));
        }
        Path dir = Paths.get(props.storage().workRoot(), req.jobId().toString(), "song");
        Files.createDirectories(dir);

        String mood = req.mood() == null || req.mood().isBlank() ? "warm and playful" : req.mood();
        // Bucket the free-form mood into a rich, Suno-ready style + description so each
        // episode gets a varied, professionally-described backing track instead of one
        // generic prompt. Buckets mirror the orchestrator's mapMoodToBucket / bible music
        // README (energetic | thoughtful | calm + warm default).
        String[] sp = instrumentalStyleFor(mood);
        String style = sp[0];
        // Story E2 (slice) — give the score a clear EMOTIONAL ARC matching the
        // fixed episode structure (hook → build → climax → warm settle) so the
        // music supports the story dramaturgically instead of looping one flat
        // mood. Appended AFTER bucketing so it never changes the chosen bucket.
        // Deliberately free of bucket keywords (energetic/calm/curious/…).
        String prompt = sp[1] + " " + SCORE_ARC;

        Path music = suno.generate(prompt, style, dir.resolve("instrumental.mp3"));
        return ResponseEntity.ok(new InstrumentalResponse(
                music == null ? null : music.toString(), music != null));
    }

    /**
     * Maps a free-form episode mood to a rich, mood-specific Suno style + GPT description
     * prompt. Bucketing keywords match the orchestrator's {@code mapMoodToBucket} and
     * {@code bible/music/README.md} so behaviour stays consistent across the pipeline:
     *
     *   - energetic   : energetic, adventure, excited, playful, silly, chaotic
     *   - thoughtful  : thoughtful, curious, wonder, discovery, mystery
     *   - calm        : cozy, quiet, bedtime, sleepy, gentle (the calm/default bucket)
     *   - warm        : everything else — the safe, cheerful "Tiny Chicken World" default
     *
     * Every style stays preschool-safe (no harsh, dark or scary sounds), names concrete
     * instruments + tempo, and always carries an explicit "instrumental, no vocals" cue.
     *
     * @return a two-element array: [0] = style, [1] = gpt_description_prompt.
     */
    private String[] instrumentalStyleFor(String mood) {
        String m = mood.toLowerCase();

        // ENERGETIC — adventure, romps, silly chases through the tiny world.
        if (m.contains("energetic") || m.contains("adventure") || m.contains("excited")
                || m.contains("playful") || m.contains("chaotic") || m.contains("silly")) {
            String style = "upbeat children's cartoon adventure instrumental, bright and bouncy, "
                    + "120-132 BPM, plucky pizzicato strings, perky staccato woodwinds (clarinet, "
                    + "piccolo), tuned hand claps, bouncing marimba and xylophone, light snappy "
                    + "shaker-and-tambourine groove, cheeky tuba bass, sunny major key, "
                    + "playful and energetic, wholesome, no harsh or scary sounds, "
                    + "instrumental, no vocals; mood: " + mood;
            String prompt = "Bouncy, adventurous background music for a preschool cartoon about three "
                    + "little chickens — Pip, Mo and Bo — scampering and exploring their cozy tiny "
                    + "world. Keep it fun, light and energetic but gentle enough for ages 3-6. "
                    + "Mood: " + mood + ".";
            return new String[]{style, prompt};
        }

        // THOUGHTFUL — curiosity, wonder, little discoveries.
        if (m.contains("thoughtful") || m.contains("curious") || m.contains("wonder")
                || m.contains("discovery") || m.contains("mystery")) {
            String style = "gentle curious children's cartoon instrumental, soft and inquisitive, "
                    + "84-96 BPM, sparkling music-box and celesta, twinkly glockenspiel, "
                    + "tip-toeing pizzicato strings, warm vibraphone, mallet-finger marimba, "
                    + "airy flute, light brushed percussion, sense of wonder and tiny discovery, "
                    + "bright but soft major key, wholesome and tender, instrumental, no vocals; "
                    + "mood: " + mood;
            String prompt = "Curious, wonder-filled background music for a preschool cartoon where three "
                    + "little chickens — Pip, Mo and Bo — discover something new in their tiny world. "
                    + "Soft, twinkly and inquisitive, full of gentle wonder for ages 3-6. "
                    + "Mood: " + mood + ".";
            return new String[]{style, prompt};
        }

        // CALM — cozy, quiet, bedtime, sleepy moments in the barn.
        if (m.contains("calm") || m.contains("cozy") || m.contains("quiet")
                || m.contains("bedtime") || m.contains("sleepy") || m.contains("gentle")
                || m.contains("lullaby") || m.contains("soft")) {
            String style = "calm cozy children's lullaby instrumental, slow and soothing, 64-76 BPM, "
                    + "soft fingerpicked nylon guitar, warm felt piano, gentle glockenspiel, "
                    + "mellow vibraphone, airy sustained pad, faint music box, no percussion or "
                    + "only the softest brushed shaker, tender and reassuring, warm major key, "
                    + "wholesome bedtime feel, instrumental, no vocals; mood: " + mood;
            String prompt = "Soft, soothing bedtime background music for a preschool cartoon as three "
                    + "little chickens — Pip, Mo and Bo — settle into their cozy barn nest in the "
                    + "tiny world. Calm, warm and reassuring for ages 3-6. Mood: " + mood + ".";
            return new String[]{style, prompt};
        }

        // WARM DEFAULT — the safe, cheerful everyday "Tiny Chicken World" palette.
        String style = "warm children's cartoon background instrumental, gentle and whimsical, "
                + "90-104 BPM, ukulele, glockenspiel, marimba, soft mallets, warm acoustic guitar, "
                + "light playful percussion, cozy and wholesome, sunny major key, "
                + "no harsh or scary sounds, instrumental, no vocals; mood: " + mood;
        String prompt = "Soft, cheerful background music for a preschool cartoon about three little "
                + "chickens — Pip, Mo and Bo — exploring their cozy tiny world. Warm, playful and "
                + "gentle for ages 3-6. Mood: " + mood + ".";
        return new String[]{style, prompt};
    }

    @PostMapping("/generate")
    public ResponseEntity<GenerateResponse> generate(@RequestBody GenerateRequest req) throws Exception {
        if (!suno.isEnabled()) {
            log.warn("Suno not enabled — song mode falling back to instrumental");
            return ResponseEntity.ok(new GenerateResponse(null, null, false));
        }
        Path dir = Paths.get(props.storage().workRoot(), req.jobId().toString(), "song");
        Files.createDirectories(dir);

        Path song = suno.generateSong(req.lyrics(), req.style(), dir.resolve("song.mp3"));
        // Karaoke = instrumental version using the chorus as the seed prompt.
        Path karaoke = suno.generate(req.chorus() == null ? req.lyrics() : req.chorus(),
                req.style(), dir.resolve("karaoke.mp3"));

        return ResponseEntity.ok(new GenerateResponse(
                song == null ? null : song.toString(),
                karaoke == null ? null : karaoke.toString(),
                true));
    }
}
